name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build

      - name: Rename file
        run: mv build/libs/samstestmod-1.0.0.jar build/libs/samstestmod-0.${{ github.run_number }}.${{ github.run_attempt }}.jar
          
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          # modrinth-id: AAAAAAAA
          # modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          # curseforge-id: 000000
          # curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on GitHub.
          github-token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
          github-tag: mc1.21.1-0.${{ github.run_number }}.${{ github.run_attempt }}
          version: mc1.12.1-0.${{ github.run_number }}.${{ github.run_attempt }}
          version-type: beta
